import { MicroZone } from '@crisis/types';

const DEFAULT_SENSOR = { temperature: 22, smoke: 0, gas: 5, structural: 1 };

export const MICRO_ZONES: MicroZone[] = [
  // ── Core Hub ─────────────────────────────────────────────────────────────────
  {
    id: 'hub-center',
    label: 'Primary Hub',
    type: 'core',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },

  // ── Ring Corridor Segments (8 sectors) ───────────────────────────────────────
  {
    id: 'ring-north',
    label: 'Ring Corridor North',
    type: 'corridor',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-northeast',
    label: 'Ring Corridor NE',
    type: 'corridor',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-east',
    label: 'Ring Corridor East',
    type: 'corridor',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-southeast',
    label: 'Ring Corridor SE',
    type: 'corridor',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-south',
    label: 'Ring Corridor South',
    type: 'corridor',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-southwest',
    label: 'Ring Corridor SW',
    type: 'corridor',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-west',
    label: 'Ring Corridor West',
    type: 'corridor',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'ring-northwest',
    label: 'Ring Corridor NW',
    type: 'corridor',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },

  // ── NW Wing (Zone A) ─────────────────────────────────────────────────────────
  {
    id: 'server-room',
    label: 'Server Room',
    type: 'critical',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { temperature: 24, smoke: 0, gas: 3, structural: 1 },
    nodeIds: [],
  },
  {
    id: 'utility-nw',
    label: 'Utility / Mechanical NW',
    type: 'hazard',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { temperature: 23, smoke: 0, gas: 8, structural: 1 },
    nodeIds: [],
  },
  {
    id: 'dining-nw',
    label: 'Dining Area NW',
    type: 'public',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'corridor-nw',
    label: 'Wing Corridor NW',
    type: 'corridor',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-nw-1',
    label: 'Guest Rooms NW-1',
    type: 'private',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-nw-2',
    label: 'Guest Rooms NW-2',
    type: 'private',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-nw-3',
    label: 'Guest Rooms NW-3',
    type: 'private',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-nw-4',
    label: 'Guest Rooms NW-4',
    type: 'private',
    parentZone: 'A',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },

  // ── NE Wing (Zone B) ─────────────────────────────────────────────────────────
  {
    id: 'pool',
    label: 'Pool Area',
    type: 'public',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { temperature: 28, smoke: 0, gas: 3, structural: 1 },
    nodeIds: [],
  },
  {
    id: 'utility-ne',
    label: 'Utility / Mechanical NE',
    type: 'hazard',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { temperature: 23, smoke: 0, gas: 8, structural: 1 },
    nodeIds: [],
  },
  {
    id: 'dining-ne',
    label: 'Dining Area NE',
    type: 'public',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'corridor-ne',
    label: 'Wing Corridor NE',
    type: 'corridor',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-ne-1',
    label: 'Guest Rooms NE-1',
    type: 'private',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-ne-2',
    label: 'Guest Rooms NE-2',
    type: 'private',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-ne-3',
    label: 'Guest Rooms NE-3',
    type: 'private',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-ne-4',
    label: 'Guest Rooms NE-4',
    type: 'private',
    parentZone: 'B',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },

  // ── SW Wing (Zone C) ─────────────────────────────────────────────────────────
  {
    id: 'lounge-sw',
    label: 'Lounge SW',
    type: 'public',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'corridor-sw',
    label: 'Wing Corridor SW',
    type: 'corridor',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-sw-1',
    label: 'Guest Rooms SW-1',
    type: 'private',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-sw-2',
    label: 'Guest Rooms SW-2',
    type: 'private',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-sw-3',
    label: 'Guest Rooms SW-3',
    type: 'private',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-sw-4',
    label: 'Guest Rooms SW-4',
    type: 'private',
    parentZone: 'C',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },

  // ── SE Wing (Zone D) ─────────────────────────────────────────────────────────
  {
    id: 'lounge-se',
    label: 'Lounge SE',
    type: 'public',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'corridor-se',
    label: 'Wing Corridor SE',
    type: 'corridor',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-se-1',
    label: 'Guest Rooms SE-1',
    type: 'private',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-se-2',
    label: 'Guest Rooms SE-2',
    type: 'private',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-se-3',
    label: 'Guest Rooms SE-3',
    type: 'private',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
  {
    id: 'rooms-se-4',
    label: 'Guest Rooms SE-4',
    type: 'private',
    parentZone: 'D',
    riskLevel: 0,
    sensorData: { ...DEFAULT_SENSOR },
    nodeIds: [],
  },
];
